---
- hosts: all
  sudo: True

  pre_tasks:
    - apt: name={{item}} state=present
      with_items:
        - etckeeper
  roles:
    - { role: rvm-passenger }
    - { role: mysql, mysql_root_password: password }
